class Excep2{
public static void main(String[] args0){
try{
int a,b;
int d=40/0;
System.out.println("this program will no be printed");
}
catch(Exception e){
System.out.println("arithmetic exception as divided by 0");
}
}
}